version: 0.2

phases:
  install:
    commands:
      - echo "Installation des dépendances..."
      - npm install
  pre_build:
    commands:
      - echo "Exécution des tests..."
      - npm test
      - echo "Connexion à Amazon ECR..."
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 236287214134.dkr.ecr.eu-west-3.amazonaws.com
      - REPOSITORY_URI=236287214134.dkr.ecr.eu-west-3.amazonaws.com/mon-app-react
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
  build:
    commands:
      - echo "Construction de image Docker..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Envoi de image vers ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - appspec.yml
    - scripts/**/*